apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: app:frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: frontend-volume
              mountPath: /app/build
      volumes:
        - name: frontend-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
